/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2018-10-18 16:01:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=GB18030");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"GB18030\">\r\n");
      out.write("\t\t<title>activeMethod</title>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<h1>取得Map类型request,session,application的信息</h1> <br>\r\n");
      out.write("\t\t<h2>\r\n");
      out.write("\t\t\t1.通过构造函数主动将ActionContext中的HttpRequest对象赋值给Map类型的request对象（很少用）;com.fpq.action.webElement.LoginAction1\r\n");
      out.write("\t\t\t2.实现RequestAware接口，重载setRequest方法，在接口RequestAware中调用该方式将Request对象的内容赋值给request（常用）；com.fpq.action.webElement.LoginAction2\r\n");
      out.write("\t\t</h2>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<ol>\r\n");
      out.write("\t\t\t<li>依赖于容器</li>\r\n");
      out.write("\t\t\t<li>IOC</li>\r\n");
      out.write("\t\t</ol>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<h1>取得真实类型HttpServletRequest,HttpSession,ServletContext的信息</h1> <br>\r\n");
      out.write("\t\t<h2>\r\n");
      out.write("\t\t\t1.通过ServletActionContext获取request,通过request获取session,通过session获取application（很少用）;com.fpq.action.webElement.LoginAction3\r\n");
      out.write("\t\t\t2.实现ServletRequestAware接口：重载setServletRequest方法，在接口ServletRequestAware中调用该方式将HttpServletRequest对象的内容赋值给request（很少用）；com.fpq.action.webElement.LoginAction4\r\n");
      out.write("\t\t</h2>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<ol>\r\n");
      out.write("\t\t\t<li>依赖于容器</li>\r\n");
      out.write("\t\t\t<li>IOC</li>\r\n");
      out.write("\t\t</ol>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<form name=\"f\" action=\"\" method=\"post\"> \r\n");
      out.write("\t\t\t用户名：<input type=\"text\" name=\"name\"> \r\n");
      out.write("\t\t\t<s:fielderror fieldName=\"admin.name\"> \r\n");
      out.write("\t\t\t</s:fielderror> <br/> \r\n");
      out.write("\t\t\t密码：<input type=\"text\" name=\"password\"> \r\n");
      out.write("\t\t\t<s:fielderror fieldName=\"admin.password\"> \r\n");
      out.write("\t\t\t</s:fielderror> <br/> \r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"登录\"> \r\n");
      out.write("\t\t\t<input type=\"button\" value=\"submit1\" onclick=\"javascript:document.f.action='login/login1;'document.f.submit();\"/>\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"submit2\" onclick=\"javascript:document.f.action='login/login2;'document.f.submit();\"/>\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"submit3\" onclick=\"javascript:document.f.action='login/login3;'document.f.submit();\"/>\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"submit4\" onclick=\"javascript:document.f.action='login/login4;'document.f.submit();\"/>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
